# Generated by Django 6.1.1 on 2026-09-29 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('time_limit', models.IntegerField(default=7200, help_text='Duration in seconds')),
                ('is_rated', models.BooleanField(default=True)),
                ('rate_all', models.BooleanField(default=False)),
                ('format_name', models.CharField(choices=[('icpc', 'ICPC Format'), ('ioi', 'IOI Partial Format'), ('atcoder', 'AtCoder Format')], default='icpc', max_length=20)),
                ('is_visible', models.BooleanField(default=True)),
                ('hide_scoreboard', models.BooleanField(default=False)),
                ('scoreboard_freeze', models.DateTimeField(blank=True, null=True)),
                ('access_code', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=20)),
                ('common_name', models.CharField(max_length=20)),
                ('ace_mode_name', models.CharField(default='c_cpp', max_length=30)),
                ('pygments_style', models.CharField(default='cpp', max_length=30)),
                ('template', models.TextField(blank=True, default='')),
                ('info', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('short_name', models.CharField(max_length=32)),
                ('about', models.TextField(blank=True, default='')),
                ('is_open', models.BooleanField(default=True)),
                ('member_count', models.IntegerField(default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('auth_key', models.CharField(max_length=128)),
                ('is_blocked', models.BooleanField(default=False)),
                ('online', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('ping', models.FloatField(blank=True, null=True)),
                ('load', models.FloatField(default=0.0)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('runtime_versions', models.JSONField(blank=True, default=dict)),
                ('languages', models.ManyToManyField(blank=True, to='judge.language')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, default='')),
                ('timezone', models.CharField(default='Asia/Ho_Chi_Minh', max_length=50)),
                ('points', models.FloatField(default=0.0)),
                ('performance_points', models.FloatField(default=0.0)),
                ('problem_count', models.IntegerField(default=0)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('display_rank', models.CharField(default='Newbie', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='judge.language')),
                ('organizations', models.ManyToManyField(blank=True, related_name='members', to='judge.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(help_text='Markdown/KaTeX problem statement')),
                ('time_limit', models.FloatField(default=1.0)),
                ('memory_limit', models.IntegerField(default=262144)),
                ('points', models.FloatField(default=100.0)),
                ('partial', models.BooleanField(default=False)),
                ('short_circuit', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('is_organization_private', models.BooleanField(default=False)),
                ('bendo_data', models.JSONField(blank=True, default=dict)),
                ('is_manually_managed', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('organizations', models.ManyToManyField(blank=True, to='judge.organization')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='judge.problemgroup')),
                ('types', models.ManyToManyField(blank=True, related_name='problems', to='judge.problemtype')),
                ('authors', models.ManyToManyField(blank=True, related_name='authored_problems', to='judge.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('page', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='judge.comment')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.profile')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('body', models.TextField()),
                ('publish_on', models.DateTimeField(auto_now_add=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.profile')),
            ],
        ),
        migrations.CreateModel(
            name='RatingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('volatility', models.IntegerField(default=0)),
                ('ranking', models.IntegerField(default=1)),
                ('last_rated', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='judge.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('time', models.FloatField(blank=True, null=True)),
                ('memory', models.FloatField(blank=True, null=True)),
                ('points', models.FloatField(blank=True, null=True)),
                ('result', models.CharField(blank=True, choices=[('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('OLE', 'Output Limit Exceeded'), ('RTE', 'Runtime Error'), ('IR', 'Invalid Return'), ('CE', 'Compilation Error'), ('AB', 'Aborted'), ('SC', 'Short Circuited')], max_length=5, null=True)),
                ('status', models.CharField(choices=[('QU', 'Queued'), ('P', 'Processing'), ('G', 'Grading'), ('D', 'Done')], default='QU', max_length=2)),
                ('source', models.TextField()),
                ('error', models.TextField(blank=True, default='')),
                ('is_rejudged', models.BooleanField(default=False)),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='judge.contest')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='judge.language')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='judge.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='judge.profile')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.IntegerField()),
                ('status', models.CharField(choices=[('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('OLE', 'Output Limit Exceeded'), ('RTE', 'Runtime Error'), ('IR', 'Invalid Return'), ('CE', 'Compilation Error'), ('AB', 'Aborted'), ('SC', 'Short Circuited')], max_length=5)),
                ('time', models.FloatField(default=0.0)),
                ('memory', models.FloatField(default=0.0)),
                ('points', models.FloatField(default=0.0)),
                ('total_points', models.FloatField(default=10.0)),
                ('feedback', models.TextField(blank=True, default='')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='judge.submission')),
            ],
            options={
                'ordering': ['case'],
            },
        ),
        migrations.CreateModel(
            name='ContestProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.FloatField(default=100.0)),
                ('partial', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=1)),
                ('output_prefix', models.CharField(blank=True, default='A', max_length=10)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_problems', to='judge.contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.problem')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('contest', 'problem')},
            },
        ),
        migrations.CreateModel(
            name='ContestParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_start', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(default=0.0)),
                ('cumulative_time', models.IntegerField(default=0)),
                ('tiebreaker', models.FloatField(default=0.0)),
                ('is_disqualified', models.BooleanField(default=False)),
                ('format_data', models.JSONField(blank=True, default=dict)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='judge.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_participations', to='judge.profile')),
            ],
            options={
                'unique_together': {('contest', 'user')},
            },
        ),
    ]
