# Generated by Django 6.1.1 on 2026-09-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(blank=True, default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='problem',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='problem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
