# Generated by Django 6.1.1 on 2026-10-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0003_clarification'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='cover',
            field=models.TextField(blank=True, default='/frontend/assets/images/codepro-cover.jpg'),
        ),
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.TextField(blank=True, default='/frontend/assets/icons/org-default.svg'),
        ),
        migrations.AddField(
            model_name='organization',
            name='owner_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='organization',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.CharField(blank=True, default='https://codeprooj.com', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(default='user', max_length=32),
        ),
    ]
