# Generated by Django 6.1.1 on 2026-10-06 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0004_organization_cover_organization_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(default='OFFLINE', max_length=16)),
                ('cpu_count', models.PositiveIntegerField(default=0)),
                ('memory_limit', models.PositiveIntegerField(default=0, help_text='MB')),
                ('supported_languages', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('maintenance', models.BooleanField(default=False)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'judge_workers',
            },
        ),
        migrations.CreateModel(
            name='JudgeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.CharField(max_length=80, unique=True)),
                ('priority', models.IntegerField(default=10)),
                ('status', models.CharField(default='WAITING', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_jobs', to='judge.submission')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='judge.judgeworker')),
            ],
            options={
                'db_table': 'judge_jobs',
            },
        ),
        migrations.CreateModel(
            name='JudgeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(max_length=12)),
                ('score', models.FloatField(default=0)),
                ('execution_time', models.FloatField(default=0, help_text='ms')),
                ('memory_used', models.FloatField(default=0, help_text='KB')),
                ('output_size', models.PositiveIntegerField(default=0)),
                ('compile_time', models.FloatField(default=0, help_text='ms')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='judge_result', to='judge.judgejob')),
            ],
            options={
                'db_table': 'judge_results',
            },
        ),
        migrations.CreateModel(
            name='JudgeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='INFO', max_length=12)),
                ('action', models.CharField(blank=True, max_length=64)),
                ('message', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='judge.judgejob')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='judge.judgeworker')),
            ],
            options={
                'db_table': 'judge_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='judgejob',
            index=models.Index(fields=['status', 'created_at'], name='judge_jobs_status_e83be5_idx'),
        ),
    ]
