# Generated by Django 6.1.1 on 2026-10-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0006_judge_result_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='result',
            field=models.CharField(blank=True, choices=[('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('OLE', 'Output Limit Exceeded'), ('RTE', 'Runtime Error'), ('IR', 'Invalid Return'), ('CE', 'Compilation Error'), ('SE', 'System Error'), ('IE', 'Internal Error'), ('AB', 'Aborted'), ('SC', 'Short Circuited')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='submissiontestcase',
            name='status',
            field=models.CharField(choices=[('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('OLE', 'Output Limit Exceeded'), ('RTE', 'Runtime Error'), ('IR', 'Invalid Return'), ('CE', 'Compilation Error'), ('SE', 'System Error'), ('IE', 'Internal Error'), ('AB', 'Aborted'), ('SC', 'Short Circuited')], max_length=5),
        ),
    ]
