# Generated by Django 6.1.1 on 2026-10-03 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordreset',
            name='email',
            field=models.EmailField(blank=True, db_index=True, default='', max_length=254),
        ),
    ]
