# Generated by Django 6.1.1 on 2026-09-30 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('judge', '0003_clarification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_type', models.CharField(db_index=True, default='global', max_length=32)),
                ('snapshot_key', models.CharField(db_index=True, max_length=64)),
                ('data', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContestRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(db_index=True, default=1)),
                ('solved', models.IntegerField(default=0)),
                ('score', models.FloatField(default=0.0)),
                ('penalty', models.IntegerField(default=0)),
                ('rating_before', models.IntegerField(blank=True, null=True)),
                ('rating_after', models.IntegerField(blank=True, null=True)),
                ('rating_change', models.IntegerField(default=0)),
                ('problem_details', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='judge.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_rankings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank'],
                'indexes': [models.Index(fields=['contest', 'rank'], name='ranking_con_contest_5940a7_idx'), models.Index(fields=['contest', '-solved', 'penalty'], name='ranking_con_contest_454097_idx')],
                'unique_together': {('contest', 'user')},
            },
        ),
        migrations.CreateModel(
            name='GlobalRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(db_index=True, default=1)),
                ('rating', models.IntegerField(db_index=True, default=1500)),
                ('score', models.FloatField(default=0.0)),
                ('solved', models.IntegerField(default=0)),
                ('submissions', models.IntegerField(default=0)),
                ('country', models.CharField(blank=True, db_index=True, default='Vietnam', max_length=64)),
                ('school', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('tier', models.CharField(default='Specialist', max_length=32)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rankings', to='judge.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_ranking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank'],
                'indexes': [models.Index(fields=['rank'], name='ranking_glo_rank_c35d92_idx'), models.Index(fields=['rating'], name='ranking_glo_rating_771189_idx'), models.Index(fields=['country', 'rank'], name='ranking_glo_country_c12608_idx'), models.Index(fields=['school', 'rank'], name='ranking_glo_school_13a368_idx')],
            },
        ),
        migrations.CreateModel(
            name='RatingHistoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_name', models.CharField(blank=True, default='', max_length=256)),
                ('old_rating', models.IntegerField()),
                ('new_rating', models.IntegerField()),
                ('rating_change', models.IntegerField()),
                ('rank_in_contest', models.IntegerField(default=1)),
                ('performance', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_histories', to='judge.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='ranking_rat_user_id_c816a4_idx'), models.Index(fields=['contest'], name='ranking_rat_contest_3ccb70_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_rating', models.IntegerField(db_index=True, default=1500)),
                ('max_rating', models.IntegerField(default=1500)),
                ('rank_tier', models.CharField(default='Specialist', max_length=32)),
                ('volatility', models.FloatField(default=300.0)),
                ('contests_participated', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-current_rating'],
                'indexes': [models.Index(fields=['-current_rating'], name='ranking_use_current_328066_idx'), models.Index(fields=['rank_tier'], name='ranking_use_rank_ti_6dadb0_idx')],
            },
        ),
    ]
