# Generated by Django 6.1.1 on 2026-10-09 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('judge', '0007_submission_system_verdicts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AntiCheatCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under review'), ('CONFIRMED', 'Confirmed'), ('DISMISSED', 'Dismissed'), ('APPEALED', 'Appealed'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=16)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anti_cheat_cases', to='judge.contest')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'anti_cheat_cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AntiCheatPenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('WARNING', 'Warning'), ('DISQUALIFY', 'Disqualify from contest')], max_length=16)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='anti_cheat.anticheatcase')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'anti_cheat_penalties',
            },
        ),
        migrations.CreateModel(
            name='AntiCheatAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UPHELD', 'Upheld'), ('REJECTED', 'Rejected')], default='OPEN', max_length=12)),
                ('decision', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('appellant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('penalty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='anti_cheat.anticheatpenalty')),
            ],
            options={
                'db_table': 'anti_cheat_appeals',
            },
        ),
        migrations.CreateModel(
            name='AntiCheatSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('similarity_threshold', models.PositiveSmallIntegerField(default=89)),
                ('scan_mode', models.CharField(choices=[('realtime', 'Realtime'), ('scheduled', 'Scheduled'), ('manual', 'Manual')], default='realtime', max_length=12)),
                ('min_tokens', models.PositiveSmallIntegerField(default=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anti_cheat_settings', to='judge.contest')),
            ],
            options={
                'db_table': 'anti_cheat_settings',
            },
        ),
        migrations.CreateModel(
            name='ScanJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=12)),
                ('processed', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('matches', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anti_cheat_scans', to='judge.contest')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('target_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='judge.submission')),
            ],
            options={
                'db_table': 'anti_cheat_scan_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimilarityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('algorithm_version', models.CharField(max_length=32)),
                ('source_a_sha256', models.CharField(max_length=64)),
                ('source_b_sha256', models.CharField(max_length=64)),
                ('evidence', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anti_cheat_results', to='judge.contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.problem')),
                ('submission_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anti_cheat_matches_a', to='judge.submission')),
                ('submission_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anti_cheat_matches_b', to='judge.submission')),
            ],
            options={
                'db_table': 'anti_cheat_similarity_results',
            },
        ),
        migrations.AddField(
            model_name='anticheatcase',
            name='result',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case', to='anti_cheat.similarityresult'),
        ),
        migrations.AddConstraint(
            model_name='anticheatpenalty',
            constraint=models.UniqueConstraint(fields=('case', 'user', 'kind'), name='anti_cheat_unique_penalty'),
        ),
        migrations.AddIndex(
            model_name='scanjob',
            index=models.Index(fields=['status', 'created_at'], name='anti_cheat__status_f27e9f_idx'),
        ),
        migrations.AddIndex(
            model_name='similarityresult',
            index=models.Index(fields=['contest', 'score'], name='anti_cheat__contest_163d9c_idx'),
        ),
        migrations.AddConstraint(
            model_name='similarityresult',
            constraint=models.UniqueConstraint(fields=('submission_a', 'submission_b'), name='anti_cheat_unique_pair'),
        ),
    ]
