# Generated by Django 6.1.1 on 2026-09-30 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_id', models.CharField(blank=True, default='', max_length=100)),
                ('contest_name', models.CharField(blank=True, default='', max_length=200)),
                ('old_rating', models.IntegerField(default=1500)),
                ('new_rating', models.IntegerField(default=1500)),
                ('change', models.IntegerField(default=0)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_rating_history',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('link', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=120)),
                ('avatar', models.CharField(blank=True, default='', max_length=300)),
                ('cover', models.CharField(blank=True, default='', max_length=300)),
                ('bio', models.TextField(blank=True, default='')),
                ('country', models.CharField(blank=True, default='Vietnam', max_length=100)),
                ('school', models.CharField(blank=True, default='', max_length=180)),
                ('organization', models.CharField(blank=True, default='', max_length=180)),
                ('website', models.URLField(blank=True, default='', max_length=255)),
                ('github', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_rating', models.IntegerField(default=1500)),
                ('max_rating', models.IntegerField(default=1500)),
                ('rank', models.CharField(default='Specialist', max_length=50)),
                ('contest_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_rating', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_ratings',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='vi', max_length=30)),
                ('theme', models.CharField(default='dark', max_length=30)),
                ('editor_theme', models.CharField(default='vs-dark', max_length=50)),
                ('editor_keymap', models.CharField(default='standard', max_length=30)),
                ('tab_size', models.IntegerField(default=4)),
                ('default_code_language', models.CharField(default='CPP17', max_length=30)),
                ('timezone', models.CharField(default='Asia/Ho_Chi_Minh', max_length=60)),
                ('email_notifications', models.BooleanField(default=True)),
                ('contest_notifications', models.BooleanField(default=True)),
                ('system_notifications', models.BooleanField(default=True)),
                ('privacy_profile', models.CharField(default='public', max_length=20)),
                ('privacy_submissions', models.CharField(default='public', max_length=20)),
                ('privacy_activity', models.CharField(default='public', max_length=20)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_settings',
            },
        ),
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_submissions', models.IntegerField(default=0)),
                ('accepted_submissions', models.IntegerField(default=0)),
                ('wrong_answers', models.IntegerField(default=0)),
                ('compilation_errors', models.IntegerField(default=0)),
                ('runtime_errors', models.IntegerField(default=0)),
                ('time_limit_exceeded', models.IntegerField(default=0)),
                ('memory_limit_exceeded', models.IntegerField(default=0)),
                ('solved_problems', models.IntegerField(default=0)),
                ('attempted_problems', models.IntegerField(default=0)),
                ('contests', models.IntegerField(default=0)),
                ('contest_wins', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_statistics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_statistics',
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_key', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(default='🏆', max_length=50)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_achievements',
                'ordering': ['-unlocked_at'],
                'unique_together': {('user', 'badge_key')},
            },
        ),
    ]
