# Generated by Django 6.1.1 on 2026-10-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_auth', '0002_passwordreset_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authsession',
            name='session_token_hash',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='otp_hash',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='otp_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='token_hash',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
